name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build docker images
        run: docker build --rm . --file Dockerfile -t local
      - name: Create Markdown files
        run: docker run -v $PWD:/opt/OrgFiles local publish.el
      - name: Commit new README file
        run: |
          git config user.name "Microsoft Army"
          git config user.email github-actions@github.com
          git add readme.md
          git commit -m "docs: report battle results"
          git push
